### ISSUE TITLE
création des opérateurs \subset, \subseteq et leurs frères \supset et \supseteq

### ISSUE THREAD

**Issue by domitouist** [touist/touist#170]
Tout est dans l'objet du ticket !
Actuellement, TouIST ne supporte pas les opérateurs "sous ensemble de" et il faut écrire l'ensemble des sous-ensembles explicitement (et leur nombre est exponentiel au cardinal de l'ensemble initial) et utiliser l'opérateur "appartient". Donc ce serait volontier que j'ajouterais un ticket "opérations sur les ensembles utilisables dans les bigand et bigor".

Exemple :
Actuellement on écrit : 
```
$E = [S1,S2,S3]
$A = [a,b]
$Set(S1) = [a,b]
$Set(S2) = [a]
$Set(S3) = [a,c]

bigand $x in $E when subset($Set($x),$A):
    $x
end
```

Et on aimerait bien pouvoir écrire de manière alternative : 
```
$A = [a,b]

bigand $S subseteq $A:
  $S
end 
```
REMARQUE : dans le premier cas on écrit le nom du ss-ensemble, alors que dans le second c'est son contenu qu'on écrit ! (c'est-à-dire que dans le premier cas, il faudrait afficher `$Set(sx)` à la place de `$x`). La première écriture est donc plus générale, mais au prix de devoir explicitement énumérer tous les sous-ensembles... Donc pouvoir faire les deux ce serait bien.

**Comment by maelvalais** [comment]
Bonjour !

J'ai repris le travail de @francing (#174) sur l'opérateur `powerset()`. J'ai dû "rassembler" les différents types d'ensembles, et grâce à cela, on pourra bientôt faire des ensembles d'ensembles !

Dans ma version expérimentale, je peux écrire
```
bigand $S in powerset([a,b,c]):
    bigor $element in $S:
        $element
    end
end
```
(cet exemple n'a pas tellement de sens)

J'aurais une petite question pour continuer mes expérimentations : à quelles formules s'attendrait-on avec l'écriture du message précédent : 
```
bigand $S subseteq $A:
    $S
end
```
Comment voudrait-on transformer l'ensemble $S en formule ?

Merci !!

Maël

**Comment by domitouist** [comment]
hello !

  * si |$A = [a, b, c], alors $S in powerset($A) et $S subseteq $A
    affichant $S||||devraient tous les deux afficher tous les
    sous-ensembles de $S|
      o |[]|||
      o |[a] [b] [c] |||
      o |[a, b] [a, c] [b, c]|||
      o |[a, b, c]|

  * Si $A = [a], [b,c]] alors $S |in powerset($A) et $S subseteq $A
    affichant $S||||devraient tous les deux afficher tous les
    sous-ensembles de $S|
      o []
      o [a], [b, c]
      o [[a], [b, c]]
  * Il me semble que nous avions également convenu que si $S = [a] alors
    $S* = a


ça répond à ta question ? Fred, Olivier, c'est bien ce que nous avions 
convenu ?

-- Domi

|
|
