### ISSUE TITLE
Erreur d'affichage concernant le symbole d'inclusion ensembliste

### ISSUE THREAD

**Issue by domitouist** [touist/touist#171]
bonjour,
le fichier ci-dessous correspond à une entrée TouIST valide mais ne s'affiche pas correctement à l'écran. Pourtant, en envoyant cette formule au solveur SAT, ça marche bien. (Donc, erreur seulement d'affichage.)
-- Domi
[ETY.txt](https://github.com/touist/touist/files/295817/ETY.txt)

**Comment by maelvalais** [comment]
Effectivement, c'est un beau bug ! J'ai proposé une correction dans #173

**Comment by maelvalais** [comment]
Voilà un zip du "distribuable" : [touist-v1.1.3-10-ge759f6b-windows-x64.zip](https://github.com/touist/touist/files/297316/touist-v1.1.3-10-ge759f6b-windows-x64.zip)
