### ISSUE TITLE
Problème d'import dans TouIST

### ISSUE THREAD

**Issue by domitouist** [touist/touist#172]
bonjour,
Lorsqu'on importe des fichiers avec le bouton prévu à cet effet, il y a parfois des choses qui disparaissent. Par exemple, dans le fichier attaché ci-joint, la parenthèse située à la ligne 11 disparait après import dans TouIST.
-- Domi
[t3.txt](https://github.com/touist/touist/files/295824/t3.txt)

**Comment by maelvalais** [comment]
Ah oui, la fonction d'import fait vraisemblablement n'importe quoi... Je suppose qu'il y a un bug dans `uploadFile()` dans `BaseDeClauses.java:118`. Faudra que quelqu'un y jette un coup d'oeil.
