### ISSUE TITLE
Problème avec ((p => q) and (q => r)) => r

### ISSUE THREAD

**Issue by maelvalais** [touist/touist#177]
Sur la version v1.1.4, le code touistl 

```
begin formula
((p => q) and (q => r)) => r
end formula
```

plante avec l'erreur

```
Fatal error: exception Failure("is_conj: unexpected value p => q")
```

Ce problème est apparu à la suite du PR #176 où on a tenté de corriger le problème du `(a=>b)=>c`

**Comment by maelvalais** [comment]
@olzd Voilà le problème en question :)

**Comment by maelvalais** [comment]
Je suis à 95% sûr que c'est lié au fait que dans `cnf.ml`, [ligne 84](https://github.com/touist/touist/blob/master/touist-translator/src/cnf.ml#L84), il manque un match sur `CImplies`, et du coup ça va dans le cas `_,_`...

Je crois que `CImplies`, `CEquiv` et `CXor` n'ont pas été complètement codés dans la traduction cnf :disappointed_relieved:

**Comment by olzd** [comment]
Je dirais plutôt que le problème se situe dans les lignes [92-97](https://github.com/touist/touist/blob/master/touist-translator/src/cnf.ml#L92-L97) où on utilise les variables `x` et `y` au lieu de `x'` et `y'`.

En tout cas en faisant le changement l'erreur ne se produit plus.

**Comment by maelvalais** [comment]
Bien vu ! 

Je crois que cette partie du code mériterait un gros refactoring (et plein de commentaires). Pour le moment, je push les modifications proposées par @olzd. Merci à toi :)

**Comment by olzd** [comment]
En fait, après réflexion je ne suis pas sûr que ce soit la bonne solution sans tests plus poussés.

**Comment by maelvalais** [comment]
@olzd Tu penses quoi des grosses modifs dans #180 ? Désolé pour le dérangement :sweat_smile:
