### ISSUE TITLE
Cardinalité

### ISSUE THREAD

**Issue by QuentinCohenSolal** [touist/touist#222]
Bonjour,

J'aurais aimé connaître la syntaxe pour les contraintes de cardinalité. J'ai utilisé le code suivant : 
```
$a = [a,b,c]
exact(2, $i , $a , p($i))
```

Cela déclenche le message d'erreur :  `line 2, col 13: syntax error after '$i' and before ','`.

Merci beaucoup.

**Comment by maelvalais** [comment]
Bonjour,
`exact(2,[a,b,c])` va générer une formule telle que il n'y ait qu'exactement deux valuations à vrai et le reste à faux parmi [a,b,c] (lorsque le solveur va chercher un modèle).

@oGasquet @FredMaris pourront donner une explication plus claire je pense :)

**Comment by QuentinCohenSolal** [comment]
D'accord, merci beaucoup. 

Mais alors il n'est possible d'appliquer "exact" que sur un ensemble de formules et non sur une formule paramétrée par un ensemble ? Je m'explique.

Actuellement, je peux faire ça : 

$E = [x,y,z]
bigand $i in $E: 
		exact(2,[O($i,a),O($i,b),O($i,c)]) 
end

Alors que j'aurais aimé faire ça : 
$E = [x,y,z]

bigand $i in $E: 
		exact(2,$j,[a,b,c],O($i,$j)) 
end

afin de ne pas avoir à énumérer toutes les formules manuellement et ainsi de faire des choses plus compliquées et aussi de manière plus compacte.

Est-ce possible ? 
Merci.

**Comment by maelvalais** [comment]
Je viens d'en parler à @oGasquet.
Cette version du `exact` n'est pas (encore ?) implémentée mais effectivement, ça serait bien utile ! Car dans l'état, `exact` n'est pas très utile car il faut écrire à la main les ensembles :confused:

Ou bien il faudrait un truc qui permette de générer un ensemble, par exemple `gen(var,ensemble,proposition)`. Du coup ça donnerait : 
```
$E = [x,y,z]

bigand $i in $E:
    let $F = gen($i,[a,b,c],O($i,$j))
    exact(2,$F)
end
```

**Comment by QuentinCohenSolal** [comment]
D'accord,  merci beaucoup.

**Comment by maelvalais** [comment]
Bonjour @QuentinCohenSolal ,
Bonne nouvelle !!! J'ai implémenté dans la v2.3.0 une petite fonctionnalité qui permet de "générer" des sets un peu comme expliqué précédemment. Désolé pour le temps qu'il a fallu !

La syntaxe est hyper simple : par exemple, `O([a,b,c])` va générer le set `[O(a) O(b) O(c)]`.

C'est un peu dans l'esprit que ce que vous aviez proposé 
Donc c'est très proche de la syntaxe dans votre précédent message : le code 
```
$E = [x,y,z]

bigand $i in $E: 
    exact(2,$j,[a,b,c],O($i,$j)) 
end
```
va donc être maintenant écrit

```
$E = [x,y,z]
bigand $i in $E: 
    exact(2,O($i,[a,b,c]))
end
```

J'espère que ça conviendra ; si ça n'est pas suffisamment expressif, j'améliorerai !

Bien cordialement,

Maël
