### ISSUE TITLE
Non prise en charge de HiDPI

### ISSUE THREAD

**Issue by Vexored** [touist/touist#224]
![croquis 57](https://cloud.githubusercontent.com/assets/25966048/23508418/da1cba60-ff51-11e6-9694-876d15b616a3.png)
Bonjour, malheureusement votre logiciel ne prend pas en charge correctement les hautes résolutions. Concrètement même si dans les paramètres Windows, l'option pour agrandir l'interface a 200%, le logiciel reste en tout petit.

Merci :)

**Comment by maelvalais** [comment]
Ah zut, problème pas évident...
Il y a par exemple [cette](http://stackoverflow.com/questions/15659044/how-to-set-the-dpi-of-java-swing-apps-on-windows-linux) question sur stackoverflow mais pas de solution facile pour le framework Swing que nous utilisons (en java).
Comme quoi ça serait super de pouvoir porter l'interface en utilisant les technos web !
