### ISSUE TITLE
Interface Graphique et retour à la ligne et Controles d'édition

### ISSUE THREAD

**Issue by tpelado** [touist/touist#225]
Le retour à la ligne sur l'interface graphique n'apparait pas si la ligne suivante commence par une parenthèse.
![retour](https://cloud.githubusercontent.com/assets/25641016/23508483/395103f6-ff52-11e6-8ad7-98af933c7cf4.png)

Aussi, il est impossible de se déplacer mot par mot en maintenant control et en utilisant les flèches directionnelles.  (Control + delete supprime bien un mot entier)

**Comment by maelvalais** [comment]
Merci pour le bug report ! J'espère que la première séance de TP s'est bien passée 😄 
Effectivement, deux bugs : 
- [ ] une ligne commençant par une parenthèse est mal affichée dans l'affichage latex
- [ ] ctrl+left devrait sauter un mot entier sous windows/linux (ou alt+left sur mac)

Je pourrai régler le premier problème assez facilement ; pour le second problème je ne sais pas trop :S

**Comment by tpelado** [comment]
dans les 2 cas le bug respectif est fixé

Bravo pour la réactivité :D

**Comment by maelvalais** [comment]
Les corrections sont dans la [v2.1.3](https://github.com/touist/touist/releases/tag/v2.1.3) !
