### ISSUE TITLE
Add remplacement into formulas

### ISSUE THREAD

**Issue by maelvalais** [touist/touist#276]
![img_2624](https://user-images.githubusercontent.com/2195781/28129558-0d67837e-6734-11e7-9e5a-3b7b887c14b8.JPG)

**Comment by JulienVianey** [comment]
So, we should be able to write in touistl formulas like `(A)[B := C for B in D]` with `A` and `C` beeing formulas, `B` beeing a  proposition and `D` a set. `C` may (should ?) contain `B`.
Then each value in `D` present in `A` will be replaced by `C` and each occurence of `B` in `C` will be replaced by the corresponding element of `D`.

I hope this is clear and correct. If I'm wrong please correct me.

**Comment by maelvalais** [comment]
Looks perfect!

**Comment by maelvalais** [comment]
![img_6569](https://user-images.githubusercontent.com/2195781/34061903-4bb08334-e1ea-11e7-9f7b-05c351b493f2.jpg)
En touist:
```
(a ⋀ b) [$e / $e ⋀ c for $e in [a,b]]
```
