### ISSUE TITLE
Pb with Java >9 on MAC OS

### ISSUE THREAD

**Issue by EmmanuelADAM** [touist/touist#308]
On MacOs, with Java > 9 (I have the issue with Java 10), launching Touist by double-clicking on the Jar File doesn't work. 
From a terminal (java -jar touist.jar), I have this error 
java.lang.NoClassDefFoundError: com/apple/eawt/OpenFilesHandler
This is due to the fact that some java classes specific to apple have been removed since java version >9.
To launch touist on Mac, I use : 
/Library/Java/JavaVirtualMhines/jdk1.8.0_152.jdk/Contents/Home/bin/java -jar touist.jar
and it works !

**Comment by maelvalais** [comment]
Well received! I'll take a look

**Comment by maelvalais** [comment]
I reproduced the bug, you were right! The `eawt` classes were removed from Java 9. I think there it has been replaced by a more platform independent thing (I began writing a fix for this in PR #301, more specifically a147945).

So for now `TouIST.jar` isn't compatible with Java 9 (I'll write a notice on the README) but I'll try to finish the PR asap!
