### ISSUE TITLE
Latex gets frozen on windows

### ISSUE THREAD

**Issue by fsancho** [touist/touist#309]
First, congratulations for TouIST. 
We have a touist file with the wumpus planning problem, and it works fine from command-line in linux (latex generation and solver), but when we try to use it in windows (10) using the GUI, it gets frozen during the latex generation, and we must kill the app.
Must we take any care with latex in windows version?, any advice?
Thanks in advance.

**Comment by maelvalais** [comment]
Hi! Merry Christmas!! 🎄
We found some bugs that sound like this one. Would you mind sharing a minimal working example (the touist file) so that we can reproduce?

Thanks for the help!!

**Comment by fsancho** [comment]
Hi Maël,

Thanks a lot for your fast reply!!!

Here you can find several versions of the same problem (variants in order
to see if I can find the bug), the wumpus....

We are trying  to use your software for our "Logic for Computer Science"
course in University of Seville. After Christmas we will introduce some
simple examples that work fine under windows/linux: Graph coloring, queens,
sudoku, rectangles,... In last years we used mainly Prover9/Maze4, but
Touist Language feels more natural for students to write bigger problems.

Logic course (in spanish, propositional and first order):
http://www.cs.us.es/~fsancho/?p=logica-informatica-2018-19

Please, let me know if I can help in anything else...

One more question, in Linux we can use the command-line version with no
previous Ocaml installation... but it seems that we have to install Ocaml
to use it in windows, and it is no so comfortable for stuudetns,... are we
right or is it possible to make use of comand-line touist directly?

All the best, and "Feliz Navidad"!!

Fernando Sancho (http://www.cs.us.es/~fsancho/)

**Comment by maelvalais** [comment]
cc @FredMaris, @oGasquet

**Comment by fsancho** [comment]
Hi Maël,

It sounds womderful... will it work as the linux cli version? (the same
options). Maybe in this way  it is easy to integrate the process with other
editors, like VSCode, emcas, Vim or Notepad++, or indeed to build any other
wrap with any other tool via the generated files along the process.

Any solution to provide easy access for students will be useful!

Thanks a lot,
Fernando

**Comment by maelvalais** [comment]
It will be the exact same experience 😀

I'm sorry for the poor Java GUI, I'm pretty much giving up, it's too much hassle 🤭

About vscode, I also made a small extension that helps using touist (color highlighting and even linter !).

![screenshot](https://user-images.githubusercontent.com/2195781/50496593-607d2400-0a31-11e9-9c55-90ae962ba995.png)

I think our best chance would be vscode + touist CLI, but the color highlighting could be easily done for Sublime and Atom as they both use the same tmLanguage format (see in the [vscode extension I maintain](https://github.com/touist/touist-vscode/tree/master/syntaxes))

**Comment by fsancho** [comment]
... no worries!, it is always a great deal using Java to manage a clean
interface, and it seems that every day harder and harder...

I am using your VSCode extension from the very first day I found touist,
and it works fine and easy... would it not be better to prepare (at least
for windows) all the environment for Vscode/Sublime/Atom?

**Comment by maelvalais** [comment]
By _all the environment for vscode/sublime/atom_ do you mean publish all necessary extensions/plugins so that color highlighting is available for everyone easily?

Btw, in the meantime of #310, I think it is still possible to use `touist` from the jar releases (the `touist` binary in them are statically linked and includes everything). Here is what it looks like:

![0645508b-0f0a-4869-8188-b9af96cff59a](https://user-images.githubusercontent.com/2195781/50557086-f8a13480-0ce1-11e9-82f0-df9451549a31.gif)

**Comment by fsancho** [comment]
Yes, it works fine! I have been testing it and it does everything we do in linux. So the students can use it easily (in 1 week) for longer cases also. Thanks!

Regarding the vscode extension I was thinking in proviiding all the capabilities of current java GUI inside these editors. For example, in VScode, using Markdown+Math extension it must be possible to show the formulas rendered in latex, and I suppose that all the flow process to write(with current highlithing) +render(markdown+mathjax/Katex)+solve+show solution(indeed, filter them) must be possible in there... and probably it is easier to maintain than the Java GUI.

**Comment by maelvalais** [comment]
Totally agree on the that: maintaining a vscode/atom/sublime extension would be easier than maintaining this hell of a Java GUI. And the overall experience would be better for people as Vscode/atom have excellent text editing feature sets.

All we need is someone to help me build it, it would begin in [`extension.ts`](https://github.com/touist/touist-vscode/blob/master/src/extension.ts) but I don't really have the time 😇

**Comment by fsancho** [comment]
Let me see if I can help in some way: 
I have 3 good students from the "Logic for Computer Science" course this year (they will use your software after christmas) that want to do something in the next months related with the topic. I can propose them to work in maintaining the extension if you agree...  I am pretty sure that it is a good project to get into the topic and play around with nice tools.

**Comment by maelvalais** [comment]
Sure, that would be great. They can either build up on what I began with touist-vscode or build from scratch, whatever they like; I can give you the proper rights to the extension repo so that you can add them to the project. Also, I'll give you a way to push the extension (with `vsce`)
