### ISSUE TITLE
Ajout d'export Latex/PDF du TouisL

### ISSUE THREAD

**Issue by aheba** [touist/touist#95]
permettre à l'utilisateur d'exporter sous format Latex ou PDF le rendu affiché de touistL

aussi lors de l'affichage latex, les $i doit correspondre à la variable i par exemple A($i) and B($i) ====> latex : A(i) ^ B(i)

**Comment by maelvalais** [comment]
On peut maintenant faire `touistc -sat --latex file.touistl` depuis la v2.2.2 (PR #235)

C'est moins facile à utiliser qu'avec une interface mais du coup moins de travail 😄 

Je ferme.
